name: grunt_gen_example
version: 1.0.0+1
publish_to: none
description: A sample project showcase generating workers
environment: 
  sdk: '>=2.15.0 <3.0.0'
  flutter: '>=1.20.0'
dependencies: 
  build_web_compilers: ^3.2.2
  grunt_web_worker_gen: ^0.8.7+1
  worker_service: ^0.7.4
  sunny_services: ^1.10.0
  pfile: ^2.2.0
  flutter: 
    sdk: flutter
dev_dependencies: 
  build_config: ^1.0.0
  build_runner: ^2.1.10
  build_web_compilers: ^3.2.2
flutter: 
  assets: 
    - ancient_task.grunt.dart.js
