name: grunt_gen_example
version: 1.0.0+1
publish_to: none
description: A sample project showcase generating workers
environment: 
  sdk: '>=2.15.0 <3.0.0'
  flutter: '>=1.20.0'
dependencies: 
  build_web_compilers: ^4.0.3
  grunt_web_worker_gen: 
    path: /Users/ericm/aesthetika/checkout/ericmartineau/grunt_web_worker_gen
  worker_service: 
    path: /Users/ericm/aesthetika/checkout/SunnyApp/worker_service
  file_upload_service: 
    path: /Users/ericm/aesthetika/checkout/ericmartineau/file_upload_service
  pfile: 
    path: /Users/ericm/aesthetika/checkout/SunnyApp/pfile
  flutter: 
    sdk: flutter
dev_dependencies: 
  build_config: ^1.1.1
  build_runner: 2.4.4
flutter: 
  assets: 
    - ancient_task.grunt.dart.js
