name: grunt_gen_example
version: 1.0.0+1
publish_to: none
description: A sample project showcase generating workers
environment: 
  sdk: '>=2.15.0 <3.0.0'
  flutter: '>=1.20.0'
dependencies: 
  build_web_compilers: ^3.2.3
  grunt_web_worker_gen: 
    path: /Users/ericm/sunny/local_plugins/grunt_web_worker_gen
  worker_service: 
    path: /Users/ericm/sunny/local_plugins/worker_service
  file_upload_service: 
    path: /Users/ericm/sunny/local_plugins/file_upload_service
  pfile: 
    path: /Users/ericm/sunny/local_plugins/pfile
  flutter: 
    sdk: flutter
dev_dependencies: 
  build_config: ^1.1.0
  build_runner: ^2.2.1
flutter: 
  assets: 
    - ancient_task.grunt.dart.js
