name: grunt_web_worker_gen
version: 0.8.7+1
description: Generates web workers
repository: https://github.com/ericmartineau/grunt_web_worker_gen
environment: 
  sdk: '>=2.16.0 <3.0.0'
dependencies: 
  analyzer: ^3.0.0
  build: ^2.2.1
  build_config: ^1.0.0
  build_runner: ^2.1.10
  build_web_compilers: ^3.2.2
  flutter_degen: ^0.8.2+1
  logging: ^1.0.2
  pedantic: ^1.11.1
  recase: ^4.0.0
  meta: ^1.3.0
  source_gen: ^1.0.5
  uri: ^1.0.0
  worker_service: ^0.7.4
dev_dependencies: 
  test: ^1.17.10
