name: grunt_web_worker_gen
version: 0.8.7+1
description: Generates web workers
repository: https://github.com/ericmartineau/grunt_web_worker_gen
environment: 
  sdk: '>=2.16.0 <3.0.0'
dependencies: 
  analyzer: ^5.13.0
  build: ^2.2.1
  build_config: ^1.1.1
  build_runner: 2.4.4
  build_web_compilers: ^4.0.3
  logging: 1.2.0
  pedantic: ^1.11.1
  recase: ^4.1.0
  meta: ^1.9.1
  source_gen: ^1.3.2
  uri: ^1.0.0
  flutter_degen: 
    path: /Users/ericm/aesthetika/checkout/SunnyApp/flutter_degen
  worker_service: 
    path: /Users/ericm/aesthetika/checkout/SunnyApp/worker_service
dev_dependencies: 
  test: ^1.17.10
