name: grunt_web_worker_gen
version: 0.8.7+1
description: Generates web workers
repository: https://github.com/ericmartineau/grunt_web_worker_gen
environment: 
  sdk: '>=2.16.0 <3.0.0'
dependencies: 
  analyzer: ^5.4.0
  build: ^2.2.1
  build_config: ^1.1.1
  build_runner: ^2.4.0
  build_web_compilers: ^3.2.2
  logging: ^1.1.1
  pedantic: ^1.11.1
  recase: ^4.1.0
  meta: ^1.9.0
  source_gen: ^1.0.5
  uri: ^1.0.0
  flutter_degen: 
    path: /Users/ericm/reliveit/checkout/SunnyApp/flutter_degen
  worker_service: 
    path: /Users/ericm/reliveit/checkout/SunnyApp/worker_service
dev_dependencies: 
  test: ^1.17.10
